
kind: Service
apiVersion: v1
metadata:
  name: kong-admin-service
  namespace: kong-dev
spec:
  selector:
    app.kubernetes.io/name: kong
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
