# kind: Pod
# apiVersion: v1
# metadata:
#   name: app
#   namespace: app-dev
#   labels:
#     app: app
# spec:
#   containers:
#   - name: app-container
#     image: hashicorp/http-echo:0.2.3
#     args:
#     - "-text=foo"
# ---
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app-dev
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: wesleywillians/kong-service:latest
        ports:
        - containerPort: 8081
        env:
          - name: PORT
            value: ":8081"
          - name: CONTENT
            value: "Bem vindo a APP"
---
kind: Service
apiVersion: v1
metadata:
  name: app-service
  namespace: app-dev
spec:
  selector:
    app: app
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "500"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "500"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: dev.sorteiofire.com.br
    http:
      paths:
      - pathType: Prefix
        path: /app
        backend:
          service:
            name: app-service
            port:
              number: 8081
